version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_fullstack
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Server
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      DB_HOST: host.docker.internal 
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: bd_fullstack
      PORT: 3001

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
